from meteostat.enumerations import Parameter

PARAMETER_DTYPES = {
    Parameter.TEMP: "Float64",
    Parameter.TAVG: "Float64",
    Parameter.TMIN: "Float64",
    Parameter.TMAX: "Float64",
    Parameter.RHUM: "Int64",
    Parameter.DWPT: "Float64",
    Parameter.PRCP: "Float64",
    Parameter.SNOW: "Int64",
    Parameter.SNWD: "Int64",
    Parameter.WDIR: "Int64",
    Parameter.WSPD: "Float64",
    Parameter.WPGT: "Float64",
    Parameter.PRES: "Float64",
    Parameter.TSUN: "Int64",
    Parameter.CLDC: "Int64",
    Parameter.VSBY: "Int64",
    Parameter.COCO: "Int64",
}

PARAMETER_DESCRIPTIONS = {
    Parameter.TEMP: "Air Temperature",
    Parameter.TAVG: "Average Air Temperature",
    Parameter.TMIN: "Minimum Air Temperature",
    Parameter.TMAX: "Maximum Air Temperature",
    Parameter.RHUM: "Relative Humidity",
    Parameter.DWPT: "Dew Point Temperature",
    Parameter.PRCP: "Precipitation",
    Parameter.SNOW: "Snowfall",
    Parameter.SNWD: "Snow Depth",
    Parameter.WDIR: "Wind Direction",
    Parameter.WSPD: "Wind Speed",
    Parameter.WPGT: "Peak Wind Gust",
    Parameter.PRES: "Sea-Level Air Pressure",
    Parameter.TSUN: "Sunshine Duration",
    Parameter.CLDC: "Cloud Cover",
    Parameter.VSBY: "Visibility",
    Parameter.COCO: "Weather Condition Code",
}
