from datetime import datetime
from typing import List
from meteostat.typing import ProviderDict
from meteostat.enumerations import Granularity, Parameter, Provider, Priority

PARAMETER_DTYPES = {
    Parameter.TEMP: "Float64",
    Parameter.TAVG: "Float64",
    Parameter.TMIN: "Float64",
    Parameter.TMAX: "Float64",
    Parameter.RHUM: "Int64",
    Parameter.DWPT: "Float64",
    Parameter.PRCP: "Float64",
    Parameter.SNOW: "Int64",
    Parameter.SNWD: "Int64",
    Parameter.WDIR: "Int64",
    Parameter.WSPD: "Float64",
    Parameter.WPGT: "Float64",
    Parameter.PRES: "Float64",
    Parameter.TSUN: "Int64",
    Parameter.CLDC: "Int64",
    Parameter.VSBY: "Int64",
    Parameter.COCO: "Int64",
}

PARAMETER_DESCRIPTIONS = {
    Parameter.TEMP: "Air Temperature",
    Parameter.TAVG: "Average Air Temperature",
    Parameter.TMIN: "Minimum Air Temperature",
    Parameter.TMAX: "Maximum Air Temperature",
    Parameter.RHUM: "Relative Humidity",
    Parameter.DWPT: "Dew Point Temperature",
    Parameter.PRCP: "Precipitation",
    Parameter.SNOW: "Snowfall",
    Parameter.SNWD: "Snow Depth",
    Parameter.WDIR: "Wind Direction",
    Parameter.WSPD: "Wind Speed",
    Parameter.WPGT: "Peak Wind Gust",
    Parameter.PRES: "Sea-Level Air Pressure",
    Parameter.TSUN: "Sunshine Duration",
    Parameter.CLDC: "Cloud Cover",
    Parameter.VSBY: "Visibility",
    Parameter.COCO: "Weather Condition Code",
}

PROVIDERS: List[ProviderDict] = [
    {
        "id": Provider.BULK_HOURLY,
        "name": "Hourly Bulk Data",
        "granularity": Granularity.HOURLY,
        "priority": Priority.LOWEST,
        "parameters": [
            Parameter.TEMP,
            Parameter.RHUM,
            Parameter.PRCP,
            Parameter.SNWD,
            Parameter.WDIR,
            Parameter.WSPD,
            Parameter.WPGT,
            Parameter.PRES,
            Parameter.TSUN,
            Parameter.CLDC,
            Parameter.COCO,
        ],
        "start": datetime(1931, 1, 1, 0, 0, 0),
        "module": "meteostat.providers.bulk.hourly",
    },
    {
        "id": Provider.BULK_DAILY,
        "name": "Daily Bulk Data",
        "granularity": Granularity.DAILY,
        "priority": Priority.LOWEST,
        "parameters": [
            Parameter.TAVG,
            Parameter.TMIN,
            Parameter.TMAX,
            Parameter.RHUM,
            Parameter.PRCP,
            Parameter.SNWD,
            Parameter.WSPD,
            Parameter.WPGT,
            Parameter.PRES,
            Parameter.TSUN,
            Parameter.CLDC,
        ],
        "start": datetime(1899, 1, 1, 0, 0, 0),
        "module": "meteostat.providers.bulk.daily",
    },
    {
        "id": Provider.BULK_DAILY_DERIVED,
        "name": "Derived Daily Bulk Data",
        "granularity": Granularity.DAILY,
        "priority": Priority.LOWEST,
        "parameters": [
            Parameter.TAVG,
            Parameter.TMIN,
            Parameter.TMAX,
            Parameter.PRCP,
            Parameter.SNOW,
            Parameter.WSPD,
            Parameter.WDIR,
            Parameter.WPGT,
            Parameter.PRES,
            Parameter.TSUN,
            Parameter.CLDC,
        ],
        "start": datetime(1931, 1, 1, 0, 0, 0),
        "module": "meteostat.providers.bulk.daily_derived",
    },
    {
        "id": Provider.BULK_MONTHLY_DERIVED,
        "name": "Derived Monthly Bulk Data",
        "granularity": Granularity.MONTHLY,
        "priority": Priority.LOWEST,
        "parameters": [
            Parameter.TAVG,
            Parameter.TMIN,
            Parameter.TMAX,
            Parameter.PRCP,
            Parameter.PRES,
            Parameter.TSUN,
        ],
        "start": datetime(1899, 1, 1, 0, 0, 0),
        "module": "meteostat.providers.bulk.monthly_derived",
    },
    {
        "id": Provider.DWD_HOURLY,
        "name": "DWD Climate Hourly",
        "granularity": Granularity.HOURLY,
        "priority": Priority.HIGHEST,
        "countries": ["DE"],
        "parameters": [Parameter.TEMP, Parameter.PRCP, Parameter.WDIR],
        "start": datetime(1939, 1, 1, 0, 0, 0),
        "license": "https://www.dwd.de/DE/service/copyright/copyright_node.html",
        "module": "meteostat.providers.dwd.hourly",
    },
    {
        "id": Provider.DWD_DAILY,
        "name": "DWD Climate Daily",
        "granularity": Granularity.DAILY,
        "priority": Priority.HIGHEST,
        "countries": ["DE"],
        "parameters": [Parameter.TEMP, Parameter.PRCP, Parameter.WDIR],
        "start": datetime(1781, 1, 1, 0, 0, 0),
        "license": "https://www.dwd.de/DE/service/copyright/copyright_node.html",
        "module": "meteostat.providers.dwd.daily",
    },
    {
        "id": Provider.ISD_LITE,
        "name": "NOAA ISD Lite",
        "granularity": Granularity.HOURLY,
        "priority": Priority.HIGH,
        "parameters": [Parameter.TEMP, Parameter.PRCP, Parameter.WDIR],
        "start": datetime(1931, 1, 1, 0, 0, 0),
        "module": "meteostat.providers.noaa.isd_lite",
    },
    {
        "id": Provider.GHCND,
        "name": "NOAA GHCN Daily",
        "granularity": Granularity.DAILY,
        "priority": Priority.HIGH,
        "parameters": [
            Parameter.TAVG,
            Parameter.TMIN,
            Parameter.TMAX,
            Parameter.PRCP,
            Parameter.SNOW,
            Parameter.WSPD,
            Parameter.WDIR,
            Parameter.WPGT,
            Parameter.TSUN,
            Parameter.CLDC,
        ],
        "start": datetime(1931, 1, 1, 0, 0, 0),
        "module": "meteostat.providers.noaa.ghcnd",
    },
    {
        "id": Provider.SYNOP,
        "name": "Meteostat SYNOP",
        "granularity": Granularity.HOURLY,
        "priority": Priority.MEDIUM,
        "parameters": [
            Parameter.TEMP,
            Parameter.RHUM,
            Parameter.PRCP,
            Parameter.SNOW,
            Parameter.SNWD,
            Parameter.WDIR,
            Parameter.WSPD,
            Parameter.WPGT,
            Parameter.PRES,
            Parameter.TSUN,
            Parameter.SGHI,
            Parameter.SDNI,
            Parameter.SDHI,
            Parameter.CLDC,
            Parameter.VSBY,
            Parameter.COCO,
        ],
        "start": datetime(2015, 8, 7, 17, 0, 0),
        "module": "meteostat.providers.meteostat.synop",
    },
    {
        "id": Provider.METAR,
        "name": "Meteostat METAR",
        "granularity": Granularity.HOURLY,
        "priority": Priority.LOW,
        "parameters": [
            Parameter.TEMP,
            Parameter.RHUM,
            Parameter.WDIR,
            Parameter.WSPD,
            Parameter.PRES,
            Parameter.COCO,
        ],
        "start": datetime(2015, 8, 7, 17, 0, 0),
        "module": "meteostat.providers.meteostat.metar",
    },
    {
        "id": Provider.MODEL,
        "name": "Meteostat Model",
        "granularity": Granularity.HOURLY,
        "priority": Priority.LOWEST,
        "parameters": [
            Parameter.TEMP,
            Parameter.RHUM,
            Parameter.PRCP,
            Parameter.WDIR,
            Parameter.WSPD,
            Parameter.WPGT,
            Parameter.PRES,
            Parameter.TSUN,
            Parameter.CLDC,
            Parameter.COCO,
        ],
        "start": datetime(2015, 8, 7, 17, 0, 0),
        "module": "meteostat.providers.meteostat.model",
    },
]
